/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAppealRouteImport } from './routes/_authenticated/appeal'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedLikesRouteImport } from './routes/_authenticated/likes'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated/matches'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminStoreReadinessRouteImport } from './routes/_authenticated/admin.store-readiness'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as ApiPublicCronAccountPurgeRouteImport } from './routes/api/public/cron/account-purge'
import { Route as ApiPublicCronStoreReconcileRouteImport } from './routes/api/public/cron/store-reconcile'
import { Route as ApiPublicWebhooksAppleRouteImport } from './routes/api/public/webhooks/apple'
import { Route as ApiPublicWebhooksBillingRouteImport } from './routes/api/public/webhooks/billing'
import { Route as ApiPublicWebhooksGoogleRouteImport } from './routes/api/public/webhooks/google'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppealRoute = AuthenticatedAppealRouteImport.update({
  id: '/appeal',
  path: '/appeal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLikesRoute = AuthenticatedLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStoreReadinessRoute =
  AuthenticatedAdminStoreReadinessRouteImport.update({
    id: '/admin/store-readiness',
    path: '/admin/store-readiness',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronAccountPurgeRoute =
  ApiPublicCronAccountPurgeRouteImport.update({
    id: '/api/public/cron/account-purge',
    path: '/api/public/cron/account-purge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronStoreReconcileRoute =
  ApiPublicCronStoreReconcileRouteImport.update({
    id: '/api/public/cron/store-reconcile',
    path: '/api/public/cron/store-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksAppleRoute = ApiPublicWebhooksAppleRouteImport.update({
  id: '/api/public/webhooks/apple',
  path: '/api/public/webhooks/apple',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksBillingRoute =
  ApiPublicWebhooksBillingRouteImport.update({
    id: '/api/public/webhooks/billing',
    path: '/api/public/webhooks/billing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksGoogleRoute = ApiPublicWebhooksGoogleRouteImport.update({
  id: '/api/public/webhooks/google',
  path: '/api/public/webhooks/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/appeal': typeof AuthenticatedAppealRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/likes': typeof AuthenticatedLikesRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/store-readiness': typeof AuthenticatedAdminStoreReadinessRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/api/public/cron/account-purge': typeof ApiPublicCronAccountPurgeRoute
  '/api/public/cron/store-reconcile': typeof ApiPublicCronStoreReconcileRoute
  '/api/public/webhooks/apple': typeof ApiPublicWebhooksAppleRoute
  '/api/public/webhooks/billing': typeof ApiPublicWebhooksBillingRoute
  '/api/public/webhooks/google': typeof ApiPublicWebhooksGoogleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/appeal': typeof AuthenticatedAppealRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/likes': typeof AuthenticatedLikesRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/store-readiness': typeof AuthenticatedAdminStoreReadinessRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/api/public/cron/account-purge': typeof ApiPublicCronAccountPurgeRoute
  '/api/public/cron/store-reconcile': typeof ApiPublicCronStoreReconcileRoute
  '/api/public/webhooks/apple': typeof ApiPublicWebhooksAppleRoute
  '/api/public/webhooks/billing': typeof ApiPublicWebhooksBillingRoute
  '/api/public/webhooks/google': typeof ApiPublicWebhooksGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/appeal': typeof AuthenticatedAppealRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/likes': typeof AuthenticatedLikesRoute
  '/_authenticated/matches': typeof AuthenticatedMatchesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/store-readiness': typeof AuthenticatedAdminStoreReadinessRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/api/public/cron/account-purge': typeof ApiPublicCronAccountPurgeRoute
  '/api/public/cron/store-reconcile': typeof ApiPublicCronStoreReconcileRoute
  '/api/public/webhooks/apple': typeof ApiPublicWebhooksAppleRoute
  '/api/public/webhooks/billing': typeof ApiPublicWebhooksBillingRoute
  '/api/public/webhooks/google': typeof ApiPublicWebhooksGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community-guidelines'
    | '/privacy'
    | '/reset-password'
    | '/safety'
    | '/support'
    | '/terms'
    | '/appeal'
    | '/discover'
    | '/likes'
    | '/matches'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/settings'
    | '/admin/settings'
    | '/admin/store-readiness'
    | '/messages/$conversationId'
    | '/admin/'
    | '/messages/'
    | '/api/public/cron/account-purge'
    | '/api/public/cron/store-reconcile'
    | '/api/public/webhooks/apple'
    | '/api/public/webhooks/billing'
    | '/api/public/webhooks/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community-guidelines'
    | '/privacy'
    | '/reset-password'
    | '/safety'
    | '/support'
    | '/terms'
    | '/appeal'
    | '/discover'
    | '/likes'
    | '/matches'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/settings'
    | '/admin/settings'
    | '/admin/store-readiness'
    | '/messages/$conversationId'
    | '/admin'
    | '/messages'
    | '/api/public/cron/account-purge'
    | '/api/public/cron/store-reconcile'
    | '/api/public/webhooks/apple'
    | '/api/public/webhooks/billing'
    | '/api/public/webhooks/google'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/community-guidelines'
    | '/privacy'
    | '/reset-password'
    | '/safety'
    | '/support'
    | '/terms'
    | '/_authenticated/appeal'
    | '/_authenticated/discover'
    | '/_authenticated/likes'
    | '/_authenticated/matches'
    | '/_authenticated/onboarding'
    | '/_authenticated/premium'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/store-readiness'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/admin/'
    | '/_authenticated/messages/'
    | '/api/public/cron/account-purge'
    | '/api/public/cron/store-reconcile'
    | '/api/public/webhooks/apple'
    | '/api/public/webhooks/billing'
    | '/api/public/webhooks/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafetyRoute: typeof SafetyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ApiPublicCronAccountPurgeRoute: typeof ApiPublicCronAccountPurgeRoute
  ApiPublicCronStoreReconcileRoute: typeof ApiPublicCronStoreReconcileRoute
  ApiPublicWebhooksAppleRoute: typeof ApiPublicWebhooksAppleRoute
  ApiPublicWebhooksBillingRoute: typeof ApiPublicWebhooksBillingRoute
  ApiPublicWebhooksGoogleRoute: typeof ApiPublicWebhooksGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appeal': {
      id: '/_authenticated/appeal'
      path: '/appeal'
      fullPath: '/appeal'
      preLoaderRoute: typeof AuthenticatedAppealRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/likes': {
      id: '/_authenticated/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof AuthenticatedLikesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/store-readiness': {
      id: '/_authenticated/admin/store-readiness'
      path: '/admin/store-readiness'
      fullPath: '/admin/store-readiness'
      preLoaderRoute: typeof AuthenticatedAdminStoreReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/account-purge': {
      id: '/api/public/cron/account-purge'
      path: '/api/public/cron/account-purge'
      fullPath: '/api/public/cron/account-purge'
      preLoaderRoute: typeof ApiPublicCronAccountPurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/store-reconcile': {
      id: '/api/public/cron/store-reconcile'
      path: '/api/public/cron/store-reconcile'
      fullPath: '/api/public/cron/store-reconcile'
      preLoaderRoute: typeof ApiPublicCronStoreReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/apple': {
      id: '/api/public/webhooks/apple'
      path: '/api/public/webhooks/apple'
      fullPath: '/api/public/webhooks/apple'
      preLoaderRoute: typeof ApiPublicWebhooksAppleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/billing': {
      id: '/api/public/webhooks/billing'
      path: '/api/public/webhooks/billing'
      fullPath: '/api/public/webhooks/billing'
      preLoaderRoute: typeof ApiPublicWebhooksBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/google': {
      id: '/api/public/webhooks/google'
      path: '/api/public/webhooks/google'
      fullPath: '/api/public/webhooks/google'
      preLoaderRoute: typeof ApiPublicWebhooksGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppealRoute: typeof AuthenticatedAppealRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedLikesRoute: typeof AuthenticatedLikesRoute
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStoreReadinessRoute: typeof AuthenticatedAdminStoreReadinessRoute
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppealRoute: AuthenticatedAppealRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedLikesRoute: AuthenticatedLikesRoute,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStoreReadinessRoute: AuthenticatedAdminStoreReadinessRoute,
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafetyRoute: SafetyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ApiPublicCronAccountPurgeRoute: ApiPublicCronAccountPurgeRoute,
  ApiPublicCronStoreReconcileRoute: ApiPublicCronStoreReconcileRoute,
  ApiPublicWebhooksAppleRoute: ApiPublicWebhooksAppleRoute,
  ApiPublicWebhooksBillingRoute: ApiPublicWebhooksBillingRoute,
  ApiPublicWebhooksGoogleRoute: ApiPublicWebhooksGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
